-- MySQL Script generated by MySQL Workbench
<<<<<<< HEAD
-- Sat Oct 12 22:23:25 2024
=======
-- Fri Oct 11 23:17:34 2024
>>>>>>> 493c0334ab1fd9f51198f946b8738d656eccf014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ConsuBanco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ConsuBanco` ;

-- -----------------------------------------------------
-- Schema ConsuBanco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ConsuBanco` DEFAULT CHARACTER SET utf8 ;
USE `ConsuBanco` ;

-- -----------------------------------------------------
-- Table `ConsuBanco`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`Client` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`Client` (
  `idClient` VARCHAR(10) NOT NULL,
  `clientName` VARCHAR(200) NOT NULL,
  `phoneNum` VARCHAR(10) NULL,
  `Clientcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsuBanco`.`Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`Branch` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`Branch` (
  `idBranch` VARCHAR(10) NOT NULL,
  `branchName` VARCHAR(100) NULL,
  `adrdres` VARCHAR(150) NULL,
  PRIMARY KEY (`idBranch`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `ConsuBanco`.`Isr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`Isr` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`Isr` (
  `idIsr` VARCHAR(10) NOT NULL,
  `rate` DECIMAL(6,1) NULL,
  `factor` INT NULL,
  `annualBase` INT NULL,
  PRIMARY KEY (`idIsr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsuBanco`.`InvestmentProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`InvestmentProduct` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`InvestmentProduct` (
  `idProduct` VARCHAR(10) NOT NULL,
  `productDescription` VARCHAR(45) NULL,
  `productCommercialName` VARCHAR(45) NULL,
  `term` VARCHAR(45) NULL,
  `investmentProfile` VARCHAR(45) NULL,
  `periodsInterest` INT NULL,
  `factor` INT NULL,
  `interestAnnualBase` INT NULL,
  `Isr_idIsr` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_InvestmentProduct_Isr1_idx` (`Isr_idIsr` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsuBanco`.`InterestPlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`InterestPlan` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`InterestPlan` (
  `idInterestPlan` VARCHAR(10) NOT NULL,
  `term` INT NULL,
  `amount` INT NULL,
  `interestRate` DECIMAL(15,3) NULL,
  `InvestmentProduct_idProduct` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idInterestPlan`),
  INDEX `fk_InterestPlan_InvestmentProduct1_idx` (`InvestmentProduct_idProduct` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsuBanco`.`Client_has_Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsuBanco`.`Client_has_Branch` ;

CREATE TABLE IF NOT EXISTS `ConsuBanco`.`Client_has_Branch` (
  `Client_idClient` VARCHAR(10) NOT NULL,
  `Branch_idBranch` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Client_idClient`, `Branch_idBranch`),
  INDEX `fk_Client_has_Branch_Branch1_idx` (`Branch_idBranch` ASC) VISIBLE,
  INDEX `fk_Client_has_Branch_Client_idx` (`Client_idClient` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
